import enum
from datetime import datetime

from sqlalchemy import Boolean, DateTime, Float, ForeignKey, String, func
from sqlalchemy import Enum as SQLEnum
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base

# ================================
# Enum
# ================================
class WasteType(str, enum.Enum):
    """3 waste categories — used by both trash_bin and classification_log."""
    RECYCLABLE = "recyclable"
    ORGANIC = "organic"
    INORGANIC = "inorganic"


class ConfirmationResult(str, enum.Enum):
    """Manager's manual confirmation status for a classification record."""
    UNCONFIRMED = "unconfirmed"
    CORRECT = "correct"
    INCORRECT = "incorrect"


# ================================
# 1. Account table
# ================================
class Account(Base):
    __tablename__ = "account"

    id: Mapped[int] = mapped_column(primary_key=True)
    username: Mapped[str] = mapped_column(String(50), unique=True, index=True, nullable=False)
    email: Mapped[str] = mapped_column(String(255), unique=True, index=True, nullable=False)
    password_hash: Mapped[str] = mapped_column(String, nullable=False)

    # Relationship
    refresh_tokens: Mapped[list["RefreshToken"]] = relationship(back_populates="account")


# ================================
# 2. Area table
# ================================
class Area(Base):
    __tablename__ = "area"

    id: Mapped[int] = mapped_column(primary_key=True)
    location_description: Mapped[str] = mapped_column(String(255), nullable=False)

    # Full MQTT topic per area — not built by concatenating a prefix (finalized decision)
    mqtt_topic_classification: Mapped[str] = mapped_column(String(255), unique=True, nullable=False)
    mqtt_topic_status_iot: Mapped[str] = mapped_column(String(255), unique=True, nullable=False)
    mqtt_topic_status_ai: Mapped[str] = mapped_column(String(255), unique=True, nullable=False)

    # Online status tracked separately for IoT / AI, updated via LWT
    iot_online: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    ai_online: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    iot_last_online: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    ai_last_online: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    # Relationship
    trash_bins: Mapped[list["TrashBin"]] = relationship(back_populates="area")
    classification_logs: Mapped[list["ClassificationLog"]] = relationship(back_populates="area")


# ================================
# 3. Trash bin table
# ================================
class TrashBin(Base):
    __tablename__ = "trash_bin"

    id: Mapped[int] = mapped_column(primary_key=True)
    area_id: Mapped[int] = mapped_column(ForeignKey("area.id"), nullable=False, index=True)

    waste_type: Mapped[WasteType] = mapped_column(SQLEnum(WasteType, name="waste_type_enum"), nullable=False)

    # Full MQTT topic per bin, e.g. truong/khu1/mucday/huuco
    mqtt_topic_fill_level: Mapped[str] = mapped_column(String(255), unique=True, nullable=False)

    height_cm: Mapped[float] = mapped_column(Float, nullable=False)
    # fill % = (H - d) / H * 100, overwritten in place — NOT stored as time-series history (finalized decision)
    current_fill_percent: Mapped[float] = mapped_column(Float, default=0.0, nullable=False)
    updated_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)

    # Relationship
    area: Mapped["Area"] = relationship(back_populates="trash_bins")


# ================================
# 4. Classification log table
# ================================
class ClassificationLog(Base):
    __tablename__ = "classification_log"

    # Auto-increment PK, used for normal join/display/pagination
    id: Mapped[int] = mapped_column(primary_key=True)

    # UUID generated by the AI script, only used to correlate MQTT + image (NOT used as PK)
    log_id: Mapped[str] = mapped_column(String(36), unique=True, index=True, nullable=False)

    area_id: Mapped[int] = mapped_column(ForeignKey("area.id"), nullable=False, index=True)

    detected_waste_type: Mapped[WasteType] = mapped_column(SQLEnum(WasteType, name="waste_type_enum"), nullable=False)
    confidence: Mapped[float] = mapped_column(Float, nullable=False)

    # NULL until the HTTP (multipart) image arrives, Backend updates it by log_id (separate image channel)
    image_url: Mapped[str | None] = mapped_column(String(500), nullable=True)
    cloudinary_public_id: Mapped[str | None] = mapped_column(String(255), nullable=True)

    confirmation_result: Mapped[ConfirmationResult] = mapped_column(
        SQLEnum(ConfirmationResult, name="confirmation_result_enum"),
        default=ConfirmationResult.UNCONFIRMED,
        nullable=False,
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    # Relationship
    area: Mapped["Area"] = relationship(back_populates="classification_logs")


# ================================
# 5. Refresh token table
# ================================
class RefreshToken(Base):
    __tablename__ = "refresh_token"

    id: Mapped[int] = mapped_column(primary_key=True)
    account_id: Mapped[int] = mapped_column(
        ForeignKey("account.id", ondelete="CASCADE"), index=True, nullable=False
    )
    token_hash: Mapped[str] = mapped_column(String(255), nullable=False, index=True)
    expires_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    revoked: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)

    # Relationship
    account: Mapped["Account"] = relationship(back_populates="refresh_tokens")