"""initialize schemas

Revision ID: 1a1d3dc0f097
Revises: 
Create Date: 2026-09-25 08:24:33.562696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a1d3dc0f097'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('khu_vuc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mo_ta_vi_tri', sa.String(length=255), nullable=False),
    sa.Column('mqtt_topic_phanloai', sa.String(length=255), nullable=False),
    sa.Column('mqtt_topic_trangthai_iot', sa.String(length=255), nullable=False),
    sa.Column('mqtt_topic_trangthai_ai', sa.String(length=255), nullable=False),
    sa.Column('iot_online', sa.Boolean(), nullable=False),
    sa.Column('ai_online', sa.Boolean(), nullable=False),
    sa.Column('iot_lan_cuoi_online', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ai_lan_cuoi_online', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mqtt_topic_phanloai'),
    sa.UniqueConstraint('mqtt_topic_trangthai_ai'),
    sa.UniqueConstraint('mqtt_topic_trangthai_iot')
    )
    op.create_table('tai_khoan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ten_dang_nhap', sa.String(length=50), nullable=False),
    sa.Column('mat_khau_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tai_khoan_ten_dang_nhap'), 'tai_khoan', ['ten_dang_nhap'], unique=True)
    op.create_table('lich_su_phan_loai',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_id', sa.String(length=36), nullable=False),
    sa.Column('khu_vuc_id', sa.Integer(), nullable=False),
    sa.Column('loai_rac_nhan_dien', sa.Enum('TAI_CHE', 'HUU_CO', 'VO_CO', name='loai_rac_enum'), nullable=False),
    sa.Column('do_chac_chan', sa.Float(), nullable=False),
    sa.Column('url_anh', sa.String(length=500), nullable=True),
    sa.Column('cloudinary_public_id', sa.String(length=255), nullable=True),
    sa.Column('ket_qua_xac_nhan', sa.Enum('CHUA_XAC_NHAN', 'DUNG', 'SAI', name='ket_qua_xac_nhan_enum'), nullable=False),
    sa.Column('thoi_gian', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['khu_vuc_id'], ['khu_vuc.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lich_su_phan_loai_khu_vuc_id'), 'lich_su_phan_loai', ['khu_vuc_id'], unique=False)
    op.create_index(op.f('ix_lich_su_phan_loai_log_id'), 'lich_su_phan_loai', ['log_id'], unique=True)
    op.create_table('refresh_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tai_khoan_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tai_khoan_id'], ['tai_khoan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_token_tai_khoan_id'), 'refresh_token', ['tai_khoan_id'], unique=False)
    op.create_index(op.f('ix_refresh_token_token_hash'), 'refresh_token', ['token_hash'], unique=False)
    op.create_table('thung_rac',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('khu_vuc_id', sa.Integer(), nullable=False),
    sa.Column('loai_rac', sa.Enum('TAI_CHE', 'HUU_CO', 'VO_CO', name='loai_rac_enum'), nullable=False),
    sa.Column('mqtt_topic_mucday', sa.String(length=255), nullable=False),
    sa.Column('chieu_cao_H_cm', sa.Float(), nullable=False),
    sa.Column('phan_tram_day_hien_tai', sa.Float(), nullable=False),
    sa.Column('cap_nhat_luc', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['khu_vuc_id'], ['khu_vuc.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mqtt_topic_mucday')
    )
    op.create_index(op.f('ix_thung_rac_khu_vuc_id'), 'thung_rac', ['khu_vuc_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_thung_rac_khu_vuc_id'), table_name='thung_rac')
    op.drop_table('thung_rac')
    op.drop_index(op.f('ix_refresh_token_token_hash'), table_name='refresh_token')
    op.drop_index(op.f('ix_refresh_token_tai_khoan_id'), table_name='refresh_token')
    op.drop_table('refresh_token')
    op.drop_index(op.f('ix_lich_su_phan_loai_log_id'), table_name='lich_su_phan_loai')
    op.drop_index(op.f('ix_lich_su_phan_loai_khu_vuc_id'), table_name='lich_su_phan_loai')
    op.drop_table('lich_su_phan_loai')
    op.drop_index(op.f('ix_tai_khoan_ten_dang_nhap'), table_name='tai_khoan')
    op.drop_table('tai_khoan')
    op.drop_table('khu_vuc')
    # ### end Alembic commands ###
