"""initialize schemas

Revision ID: 48dc967fab72
Revises: 
Create Date: 2026-09-26 12:46:37.887892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48dc967fab72'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_email'), 'account', ['email'], unique=True)
    op.create_index(op.f('ix_account_username'), 'account', ['username'], unique=True)
    op.create_table('area',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_description', sa.String(length=255), nullable=False),
    sa.Column('mqtt_topic_classification', sa.String(length=255), nullable=False),
    sa.Column('mqtt_topic_status_iot', sa.String(length=255), nullable=False),
    sa.Column('mqtt_topic_status_ai', sa.String(length=255), nullable=False),
    sa.Column('iot_online', sa.Boolean(), nullable=False),
    sa.Column('ai_online', sa.Boolean(), nullable=False),
    sa.Column('iot_last_online', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ai_last_online', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mqtt_topic_classification'),
    sa.UniqueConstraint('mqtt_topic_status_ai'),
    sa.UniqueConstraint('mqtt_topic_status_iot')
    )
    op.create_table('classification_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_id', sa.String(length=36), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('detected_waste_type', sa.Enum('RECYCLABLE', 'ORGANIC', 'INORGANIC', name='waste_type_enum'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('cloudinary_public_id', sa.String(length=255), nullable=True),
    sa.Column('confirmation_result', sa.Enum('UNCONFIRMED', 'CORRECT', 'INCORRECT', name='confirmation_result_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['area.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classification_log_area_id'), 'classification_log', ['area_id'], unique=False)
    op.create_index(op.f('ix_classification_log_log_id'), 'classification_log', ['log_id'], unique=True)
    op.create_table('refresh_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_token_account_id'), 'refresh_token', ['account_id'], unique=False)
    op.create_index(op.f('ix_refresh_token_token_hash'), 'refresh_token', ['token_hash'], unique=False)
    op.create_table('trash_bin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('waste_type', sa.Enum('RECYCLABLE', 'ORGANIC', 'INORGANIC', name='waste_type_enum'), nullable=False),
    sa.Column('mqtt_topic_fill_level', sa.String(length=255), nullable=False),
    sa.Column('height_cm', sa.Float(), nullable=False),
    sa.Column('current_fill_percent', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['area_id'], ['area.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mqtt_topic_fill_level')
    )
    op.create_index(op.f('ix_trash_bin_area_id'), 'trash_bin', ['area_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trash_bin_area_id'), table_name='trash_bin')
    op.drop_table('trash_bin')
    op.drop_index(op.f('ix_refresh_token_token_hash'), table_name='refresh_token')
    op.drop_index(op.f('ix_refresh_token_account_id'), table_name='refresh_token')
    op.drop_table('refresh_token')
    op.drop_index(op.f('ix_classification_log_log_id'), table_name='classification_log')
    op.drop_index(op.f('ix_classification_log_area_id'), table_name='classification_log')
    op.drop_table('classification_log')
    op.drop_table('area')
    op.drop_index(op.f('ix_account_username'), table_name='account')
    op.drop_index(op.f('ix_account_email'), table_name='account')
    op.drop_table('account')
    # ### end Alembic commands ###
